# Generated by Django 3.1.7 on 2021-04-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0002_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
