# Generated by Django 3.1.7 on 2021-04-04 01:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0003_auto_20210404_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
