# Generated by Django 3.1.7 on 2021-04-21 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0007_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(default=0)),
                ('body', models.CharField(max_length=400)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='Hub.user')),
                ('user_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='Hub.user')),
            ],
        ),
    ]
